times = ('Flamengo', 'Cruzeiro', 'Red Bull Bragantino', 'Palmeiras', 'Bahia', 'Fluminense', 'Atlético‑MG', 'Botafogo', 'Mirassol', 'Corinthians', 'Grêmio', 'Ceará', 'Vasco da Gama', 'São Paulo', 'Santos', 'Vitória', 'Internacional', 'Fortaleza', 'Juventude', 'Sport')
print('='*200)
print(f'Lista de times do Brasileirão: {times}')
print('='*200)
print(f'Os 5 primeiros são: {times[0:5]}')
print('='*200)
print(f'Os 4 últimos são: {times[-4:]}')
print('='*200)
print(f'Lista em ordem alfabética: {sorted(times)}')
print('='*200)
print(f'O santos está na posição {times.index('Santos')}º')